//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: xwdisk Created :
// Initializer: xwdisk.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "xwdiskFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Xwdisk_Init(Tcl_Interp* tclInterp);
extern "C" int Xwdisk_SafeInit(Tcl_Interp* tclInterp);

int Xwdisk_Init(Tcl_Interp* tclInterp)
{
        return Xwdisk_SafeInit(tclInterp);
}

int Xwdisk_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "xwdisk";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/scott/Documents/model_codes/my_codes/XWIND/diskline_test/lmod_xwdisk.dat");
        createxwdiskFunctionMap();
        return TCL_OK;

}

