//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: xwdisk
// Function body: xwdiskFunctionMap.cxx

#include    "xwdiskFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createxwdiskFunctionMap()
{


	XSModelFunction::addFunctionPointer( "xwdisk",     new XSCall<xsf77Call>(xwdisk_) );

}
