//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: xwdisk
// Function header: xwdiskFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createxwdiskFunctionMap();

extern "C"  {


	xsf77Call    xwdisk_;
}


#endif
